version: '2'
services:
    concreteslabannotator-app:
        image: concreteslabannotator
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://concreteslabannotator-mysql:3306/concreteslabannotator?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    concreteslabannotator-mysql:
        extends:
            file: mysql.yml
            service: concreteslabannotator-mysql
